### ISSUE TITLE
Completed requests appearing when Closed filter not applied 

### ISSUE THREAD

**Issue by lowellbander** [dandelion-community/aid-app#132]
![Screenshot_20220119-212807](https://user-images.githubusercontent.com/3479724/150279172-f6207753-5c27-47f1-bfd6-883ed2dba26d.png)

**Comment by bluquar** [comment]
@lowellbander  i can't repro

**Comment by bluquar** [comment]
@lowellbander can you repro?

**Comment by lowellbander** [comment]
this repro's in latest for me reliably

**Comment by lowellbander** [comment]
probably relatedly, when i mark myself as working on a request, it still shows "you recorded this" as latest activity

**Comment by lowellbander** [comment]
actually, I'm working on it doesn't seem to be persisting at all

**Comment by lowellbander** [comment]
also, when i mark as complete, the action available is still "mark as complete"
