### ISSUE TITLE
I'm working on requests but none of them appear

### ISSUE THREAD

**Issue by lowellbander** [dandelion-community/aid-app#156]
![Screenshot_20220127-183102.png](https://user-images.githubusercontent.com/3479724/151477002-c29f0cd2-d0e8-484f-b449-cf51aa219920.png)

**Comment by lowellbander** [comment]
This repros on stable! 😮

**Comment by bluquar** [comment]
Hmm not so stable after all is it

**Comment by lowellbander** [comment]
hehe <3
